### ISSUE TITLE
SvelteKitError: Not found: /socket.io/

### ISSUE THREAD

**Issue by JohnRSim** [phaserjs/template-svelte#6]
using node v22.11.0

When running I'm coming across the following 
SvelteKitError: Not found: /socket.io/

Package.json
```
{
    "name": "template-svelte",
    "description": "A Phaser 3 project template that demonstrates Svelte communication and uses Vite for bundling.",
    "version": "1.1.2",
    "repository": {
        "type": "git",
        "url": "git+https://github.com/phaserjs/template-svelte.git"
    },
    "author": "Phaser Studio <support@phaser.io> (https://phaser.io/)",
    "license": "MIT",
    "licenseUrl": "http://www.opensource.org/licenses/mit-license.php",
    "bugs": {
        "url": "https://github.com/phaserjs/template-svelte/issues"
    },
    "homepage": "https://github.com/phaserjs/template-svelte#readme",
    "keywords": [
        "phaser",
        "phaser3",
        "svelte",
        "vite"
    ],
    "scripts": {
        "dev": "node log.js dev & vite --config vite/config.dev.mjs",
        "build": "node log.js build & vite build --config vite/config.prod.mjs",
        "dev-nolog": "vite --config vite/config.dev.mjs",
        "build-nolog": "vite build --config vite/config.prod.mjs",
        "preview": "vite preview --outDir build"
    },
    "devDependencies": {
        "@sveltejs/adapter-auto": "^3.2.0",
        "@sveltejs/adapter-static": "^3.0.1",
        "@sveltejs/kit": "^2.5.8",
        "@sveltejs/vite-plugin-svelte": "^3.1.0",
        "svelte": "^4.2.17",
        "svelte-check": "^4.0.2",
        "terser": "^5.31.0",
        "tslib": "^2.6.2",
        "typescript": "^5.4.5",
        "vite": "^5.2.11"
    },
    "type": "module",
    "dependencies": {
        "phaser": "^3.87.0",
        "socket.io": "^4.8.1"
    }
}
```

```
C:\work\game>npm create @phaserjs/game@latest "zat"

> npx
> create-game zat


o----------------------------------------------------o
|      Welcome to the Phaser Template Installer      |
|            Let´s start the installation            |
|                       v1.2.7                       |
o----------------------------------------------------o

√ Select Option: » Client Framework (React, Next.js, Vue, Angular, Svelte, SolidJS or Rapier)
√ Select Template: » svelte
√ Minimal or Complete Project: » Complete (Common Phaser Scene selection)

√ We anonymously record which template was selected to help guide development.
If you don't agree, press N to Quit. Otherwise, press Y. ... yes
√ Project Downloaded

o----------------------------------------------------------o
|               Project created successfully               |
|                Thank you for using Phaser                |
|        Tell us about your game! - games@phaser.io        |
o----------------------------------------------------------o

Next steps:
1. cd zat
2. npm install
3. npm run dev

Happy coding!

C:\work\game>cd zat

C:\work\game\zat>npm install

added 83 packages, and audited 84 packages in 10s

8 packages are looking for funding
  run `npm fund` for details

3 vulnerabilities (2 low, 1 moderate)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.

C:\work\game\zat>npm run dev

> template-svelte@1.1.2 dev
> node log.js dev & vite --config vite/config.dev.mjs

Forced re-optimization of dependencies

  VITE v5.4.8  ready in 1914 ms

  ➜  Local:   http://localhost:8080/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
SvelteKitError: Not found: /socket.io/
    at resolve (C:\work\game\zat\node_modules\@sveltejs\kit\src\runtime\server\respond.js:530:13)
    at resolve (C:\work\game\zat\node_modules\@sveltejs\kit\src\runtime\server\respond.js:330:5)
    at #options.hooks.handle (C:\work\game\zat\node_modules\@sveltejs\kit\src\runtime\server\index.js:71:56)
    at Module.respond (C:\work\game\zat\node_modules\@sveltejs\kit\src\runtime\server\respond.js:327:40) {
  status: 404,
  text: 'Not Found'
}
```

**Comment by gammafp** [comment]
Hi @JohnRSim. I have followed your steps in installing the template and everything is correct on my side.
How are you using socket.io?

**Comment by JohnRSim** [comment]
I'm running a clean new setup and when I run 
npm install and then 
npm run dev

I get the error without touching the code

I have an older version of the template which is working fine - 
 3.70.0

I'm also running on windows not mac..

**Comment by JohnRSim** [comment]
I updated my version of node v22.12.0 and also tried updating sveltekit on the package but still hitting this same issue.
I'm not sure what trying to load socket.io

**Comment by JohnRSim** [comment]
on further debugging issue for me was the vite config / port -
I commented out the port and it fixed the problem.  

![image](https://github.com/user-attachments/assets/032931b6-da4a-47ff-90fb-620ca482d8f1)

**Comment by gammafp** [comment]
Nice, thank you for sharing your solution!
